production:
  url: redis://localhost:6379

local: &local
  url: redis://localhost:6379

development: *local
test: *local

# development:
#   adapter: async

# test:
#   adapter: async

# production:
#   adapter: async
