default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  username: postgres
  database: nguoimexe_development
  host: db

test:
  <<: *default
  username: postgres
  database: nguoimexe_test

staging:
  <<: *default
  database: nguoimexe_staging
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  connect_timeout: 1
  checkout_timeout: 5
  variables:
    statement_timeout: 5000

production:
  <<: *default
  database: nguoimexe_production
  username: nguoimexe
  password: password
